// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAqxLZ9eaUxTKWYtvX9_Sd3LPkQwo9FnQ',
    appId: '1:417761038287:web:44c21befeef819ec4b8cba',
    messagingSenderId: '417761038287',
    projectId: 'sanubari-store',
    authDomain: 'sanubari-store.firebaseapp.com',
    storageBucket: 'sanubari-store.firebasestorage.app',
    measurementId: 'G-70H59QTFST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJB_O_SMXTAP1-GeHgn1vrgOsEBa0RqN8',
    appId: '1:417761038287:android:21670502205869524b8cba',
    messagingSenderId: '417761038287',
    projectId: 'sanubari-store',
    storageBucket: 'sanubari-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuOIrPmXw6E4XIUWHyJB82HuLekpiCy8s',
    appId: '1:417761038287:ios:2de13d86fb11c7ff4b8cba',
    messagingSenderId: '417761038287',
    projectId: 'sanubari-store',
    storageBucket: 'sanubari-store.firebasestorage.app',
    iosBundleId: 'com.example.sanubariStore1125170135',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuOIrPmXw6E4XIUWHyJB82HuLekpiCy8s',
    appId: '1:417761038287:ios:2de13d86fb11c7ff4b8cba',
    messagingSenderId: '417761038287',
    projectId: 'sanubari-store',
    storageBucket: 'sanubari-store.firebasestorage.app',
    iosBundleId: 'com.example.sanubariStore1125170135',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAqxLZ9eaUxTKWYtvX9_Sd3LPkQwo9FnQ',
    appId: '1:417761038287:web:b841158a276e01c84b8cba',
    messagingSenderId: '417761038287',
    projectId: 'sanubari-store',
    authDomain: 'sanubari-store.firebaseapp.com',
    storageBucket: 'sanubari-store.firebasestorage.app',
    measurementId: 'G-W00EQ49ZZS',
  );
}
